import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { palettes } from '../src/lib/theme/palette.mjs';

/** @param {string} selector @param {Record<string, string>} tokens @param {string} indent */
function rule(selector, tokens, indent = '') {
	const lines = Object.entries(tokens).map(([key, value]) => `${indent}\t--${key}: ${value};`);
	return `${indent}${selector} {\n${lines.join('\n')}\n${indent}}`;
}

export function generateCss() {
	/** @param {'light' | 'dark'} scheme @param {string} indent */
	const selectors = (scheme, indent) => Object.entries(palettes[scheme]).map(([name, tokens]) =>
		rule(name === 'neutral' ? ':root' : `.shell[data-palette="${name}"]`, tokens, indent),
	).join('\n\n');
	return `/* Generated by scripts/generate-palette.mjs. Edit palette.mjs. */\n${selectors('light', '')}\n\n@media (prefers-color-scheme: dark) {\n${selectors('dark', '\t')}\n}\n`;
}

if (import.meta.url.startsWith('file:') && process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const output = fileURLToPath(new URL('../src/lib/theme/generated.css', import.meta.url));
	const css = generateCss();
	if (process.argv.includes('--check')) {
		if (readFileSync(output, 'utf8') !== css) {
			console.error('Generated palette CSS is stale. Run npm run generate:palette.');
			process.exitCode = 1;
		}
	} else {
		writeFileSync(output, css);
	}
}
